In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("mouse_viral_study.csv")

In [3]:
df

     Med_1_mL  Med_2_mL  Virus Present
0    6.508231  8.582531              0
1    4.126116  3.073459              1
2    6.427870  6.369758              0
3    3.672953  4.905215              1
4    1.580321  2.440562              1
..        ...       ...            ...
395  2.884122  3.271748              1
396  7.290855  9.488672              0
397  7.895325  8.272529              0
398  2.690592  2.674979              1
399  7.587821  9.473968              0

[400 rows x 3 columns]

In [4]:
df.isna().sum()

Med_1_mL         0
Med_2_mL         0
Virus Present    0
dtype: int64

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Med_1_mL       400 non-null    float64
 1   Med_2_mL       400 non-null    float64
 2   Virus Present  400 non-null    int64
dtypes: float64(2), int64(1)
memory usage: 9.5 KB

In [8]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [10]:
x = df.drop("Virus Present",axis = 1)
y = df["Virus Present"]

In [31]:
x_train, x_test, y_train, y_test = train_test_split(
    x,y,test_size = 0.20, random_state = 42
)

In [32]:
scaler = StandardScaler()

In [33]:
scaler

StandardScaler()

In [34]:
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [35]:
svm_c = SVC()

svm_c.fit(x_train_scaled,y_train)

SVC()

In [36]:
y_pred = svm_c.predict(x_test_scaled)

In [37]:
y_pred

array([0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1])

In [38]:
compariosn = pd.DataFrame({
    "Actual" : y_test,
    "Prediction" : y_pred
})

In [39]:
compariosn

     Actual  Prediction
209       0           0
280       1           1
33        0           0
210       0           0
93        1           1
..      ...         ...
246       0           0
227       0           0
369       0           0
176       0           0
289       1           1

[80 rows x 2 columns]

In [40]:
accuracy = accuracy_score(y_test,y_pred)*100

In [43]:
print(f"accuracy:- {accuracy:.2f}%")

accuracy:- 100.00%

In [42]:
classification = classification_report(y_test,y_pred)

In [44]:
print("Classification Report:\n",classification)

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        42
           1       1.00      1.00      1.00        38

    accuracy                           1.00        80
   macro avg       1.00      1.00      1.00        80
weighted avg       1.00      1.00      1.00        80

In [45]:
cm = confusion_matrix(y_test,y_pred)

In [46]:
print("confusion matrix:\n",cm)

confusion matrix:
 [[42  0]
 [ 0 38]]

**Conclusion**

The SVM classification model achieved 100% accuracy on the test dataset. All 80 test samples were correctly classified, with 42 samples from Class 0 and 38 samples from Class 1. Both classes achieved 100% precision, recall, and F1-score. The confusion matrix shows zero false positives and zero false negatives, indicating excellent classification performance on the test dataset.